# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIControlProf.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(553, 549)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 521, 201))
        self.groupBox.setObjectName("groupBox")
        self.SetPIDParam = QtWidgets.QPushButton(self.groupBox)
        self.SetPIDParam.setGeometry(QtCore.QRect(360, 170, 75, 23))
        self.SetPIDParam.setObjectName("SetPIDParam")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 506, 81))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.PID_Ki = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.PID_Ki.setKeyboardTracking(False)
        self.PID_Ki.setDecimals(1)
        self.PID_Ki.setMaximum(65535.0)
        self.PID_Ki.setSingleStep(0.1)
        self.PID_Ki.setProperty("value", 6.5)
        self.PID_Ki.setObjectName("PID_Ki")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.PID_Ki)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.PID_Kd = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.PID_Kd.setKeyboardTracking(False)
        self.PID_Kd.setDecimals(1)
        self.PID_Kd.setMaximum(65535.0)
        self.PID_Kd.setSingleStep(0.1)
        self.PID_Kd.setProperty("value", 2.2)
        self.PID_Kd.setObjectName("PID_Kd")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.PID_Kd)
        self.PID_Kp = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.PID_Kp.setEnabled(True)
        self.PID_Kp.setKeyboardTracking(False)
        self.PID_Kp.setDecimals(1)
        self.PID_Kp.setMaximum(65535.0)
        self.PID_Kp.setSingleStep(0.1)
        self.PID_Kp.setProperty("value", 6.3)
        self.PID_Kp.setObjectName("PID_Kp")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.PID_Kp)
        self.horizontalLayout_2.addLayout(self.formLayout_3)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.PID_KiF = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.PID_KiF.setKeyboardTracking(False)
        self.PID_KiF.setDecimals(1)
        self.PID_KiF.setMaximum(65535.0)
        self.PID_KiF.setSingleStep(0.1)
        self.PID_KiF.setProperty("value", 6.5)
        self.PID_KiF.setObjectName("PID_KiF")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.PID_KiF)
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.PID_KdF = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.PID_KdF.setKeyboardTracking(False)
        self.PID_KdF.setDecimals(1)
        self.PID_KdF.setMaximum(65535.0)
        self.PID_KdF.setSingleStep(0.1)
        self.PID_KdF.setProperty("value", 2.2)
        self.PID_KdF.setObjectName("PID_KdF")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.PID_KdF)
        self.PID_KpF = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.PID_KpF.setKeyboardTracking(False)
        self.PID_KpF.setDecimals(1)
        self.PID_KpF.setMaximum(65535.0)
        self.PID_KpF.setSingleStep(0.1)
        self.PID_KpF.setProperty("value", 6.3)
        self.PID_KpF.setObjectName("PID_KpF")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.PID_KpF)
        self.horizontalLayout_2.addLayout(self.formLayout_6)
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.PID_eL = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.PID_eL.setKeyboardTracking(False)
        self.PID_eL.setDecimals(0)
        self.PID_eL.setMaximum(65535.0)
        self.PID_eL.setSingleStep(1000.0)
        self.PID_eL.setProperty("value", 3000.0)
        self.PID_eL.setObjectName("PID_eL")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.PID_eL)
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.PID_eM = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.PID_eM.setKeyboardTracking(False)
        self.PID_eM.setDecimals(0)
        self.PID_eM.setMaximum(65535.0)
        self.PID_eM.setSingleStep(1000.0)
        self.PID_eM.setProperty("value", 2000.0)
        self.PID_eM.setObjectName("PID_eM")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.PID_eM)
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.PID_eS = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.PID_eS.setKeyboardTracking(False)
        self.PID_eS.setDecimals(0)
        self.PID_eS.setMaximum(65535.0)
        self.PID_eS.setSingleStep(1000.0)
        self.PID_eS.setProperty("value", 1000.0)
        self.PID_eS.setObjectName("PID_eS")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.PID_eS)
        self.horizontalLayout_2.addLayout(self.formLayout_7)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.PID_ecM = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.PID_ecM.setKeyboardTracking(False)
        self.PID_ecM.setDecimals(0)
        self.PID_ecM.setMaximum(65535.0)
        self.PID_ecM.setProperty("value", 200.0)
        self.PID_ecM.setObjectName("PID_ecM")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.PID_ecM)
        self.PID_ecL = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.PID_ecL.setKeyboardTracking(False)
        self.PID_ecL.setDecimals(0)
        self.PID_ecL.setMaximum(65535.0)
        self.PID_ecL.setSingleStep(1.0)
        self.PID_ecL.setProperty("value", 300.0)
        self.PID_ecL.setObjectName("PID_ecL")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.PID_ecL)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.PID_ecS = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_2)
        self.PID_ecS.setKeyboardTracking(False)
        self.PID_ecS.setDecimals(0)
        self.PID_ecS.setMinimum(0.0)
        self.PID_ecS.setMaximum(65535.0)
        self.PID_ecS.setSingleStep(1.0)
        self.PID_ecS.setProperty("value", 100.0)
        self.PID_ecS.setObjectName("PID_ecS")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.PID_ecS)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.formLayoutWidget_8 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(10, 110, 160, 81))
        self.formLayoutWidget_8.setObjectName("formLayoutWidget_8")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formLayoutWidget_8)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_15.setObjectName("label_15")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.PID_Cutoff = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_8)
        self.PID_Cutoff.setAutoFillBackground(False)
        self.PID_Cutoff.setKeyboardTracking(False)
        self.PID_Cutoff.setDecimals(2)
        self.PID_Cutoff.setMaximum(100.0)
        self.PID_Cutoff.setSingleStep(5.0)
        self.PID_Cutoff.setProperty("value", 5.0)
        self.PID_Cutoff.setObjectName("PID_Cutoff")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.PID_Cutoff)
        self.label_22 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_22.setObjectName("label_22")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.PID_SampleCycle = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_8)
        self.PID_SampleCycle.setAutoFillBackground(False)
        self.PID_SampleCycle.setKeyboardTracking(False)
        self.PID_SampleCycle.setDecimals(0)
        self.PID_SampleCycle.setMaximum(65535.0)
        self.PID_SampleCycle.setSingleStep(5.0)
        self.PID_SampleCycle.setProperty("value", 20.0)
        self.PID_SampleCycle.setObjectName("PID_SampleCycle")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.PID_SampleCycle)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_10.setObjectName("label_10")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.PID_DeadZone = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_8)
        self.PID_DeadZone.setKeyboardTracking(False)
        self.PID_DeadZone.setDecimals(1)
        self.PID_DeadZone.setMaximum(20.0)
        self.PID_DeadZone.setProperty("value", 0.0)
        self.PID_DeadZone.setObjectName("PID_DeadZone")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.PID_DeadZone)
        self.formLayoutWidget_9 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_9.setGeometry(QtCore.QRect(180, 110, 160, 81))
        self.formLayoutWidget_9.setObjectName("formLayoutWidget_9")
        self.formLayout_9 = QtWidgets.QFormLayout(self.formLayoutWidget_9)
        self.formLayout_9.setContentsMargins(0, 0, 0, 0)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget_9)
        self.label_23.setObjectName("label_23")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.PWM_MAX = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_9)
        self.PWM_MAX.setAutoFillBackground(True)
        self.PWM_MAX.setKeyboardTracking(False)
        self.PWM_MAX.setDecimals(0)
        self.PWM_MAX.setMaximum(999999999.0)
        self.PWM_MAX.setProperty("value", 690000.0)
        self.PWM_MAX.setObjectName("PWM_MAX")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.PWM_MAX)
        self.label_24 = QtWidgets.QLabel(self.formLayoutWidget_9)
        self.label_24.setObjectName("label_24")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.PWM_MIN = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_9)
        self.PWM_MIN.setAutoFillBackground(True)
        self.PWM_MIN.setKeyboardTracking(False)
        self.PWM_MIN.setDecimals(0)
        self.PWM_MIN.setMinimum(0.0)
        self.PWM_MIN.setMaximum(999999999.0)
        self.PWM_MIN.setProperty("value", 10000.0)
        self.PWM_MIN.setObjectName("PWM_MIN")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.PWM_MIN)
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget_9)
        self.label_25.setObjectName("label_25")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.PWM_STEP = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_9)
        self.PWM_STEP.setAutoFillBackground(True)
        self.PWM_STEP.setKeyboardTracking(False)
        self.PWM_STEP.setDecimals(0)
        self.PWM_STEP.setMinimum(1.0)
        self.PWM_STEP.setMaximum(99999.0)
        self.PWM_STEP.setProperty("value", 2000.0)
        self.PWM_STEP.setObjectName("PWM_STEP")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.PWM_STEP)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 260, 191, 61))
        self.groupBox_4.setObjectName("groupBox_4")
        self.SetRuningParam = QtWidgets.QPushButton(self.groupBox_4)
        self.SetRuningParam.setGeometry(QtCore.QRect(440, 120, 75, 23))
        self.SetRuningParam.setObjectName("SetRuningParam")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_4)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 160, 31))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_5.setObjectName("label_5")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.PID_SetPoint = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_4)
        self.PID_SetPoint.setKeyboardTracking(False)
        self.PID_SetPoint.setDecimals(1)
        self.PID_SetPoint.setMaximum(6000.0)
        self.PID_SetPoint.setSingleStep(2000.0)
        self.PID_SetPoint.setProperty("value", 5000.0)
        self.PID_SetPoint.setObjectName("PID_SetPoint")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.PID_SetPoint)
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 380, 271, 161))
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_5)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 161, 94))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_13.setObjectName("label_13")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.BackForward_Start = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_5)
        self.BackForward_Start.setKeyboardTracking(False)
        self.BackForward_Start.setDecimals(0)
        self.BackForward_Start.setMaximum(65535.0)
        self.BackForward_Start.setProperty("value", 100.0)
        self.BackForward_Start.setObjectName("BackForward_Start")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.BackForward_Start)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_12.setObjectName("label_12")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.BackForward_End = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_5)
        self.BackForward_End.setKeyboardTracking(False)
        self.BackForward_End.setDecimals(0)
        self.BackForward_End.setMaximum(65535.0)
        self.BackForward_End.setProperty("value", 65530.0)
        self.BackForward_End.setObjectName("BackForward_End")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.BackForward_End)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_14.setObjectName("label_14")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.BackForward_StepSize = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_5)
        self.BackForward_StepSize.setKeyboardTracking(False)
        self.BackForward_StepSize.setDecimals(0)
        self.BackForward_StepSize.setMinimum(10.0)
        self.BackForward_StepSize.setMaximum(65535.0)
        self.BackForward_StepSize.setSingleStep(500.0)
        self.BackForward_StepSize.setProperty("value", 2000.0)
        self.BackForward_StepSize.setObjectName("BackForward_StepSize")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.BackForward_StepSize)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayout_5.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.formLayout_2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_5)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 239, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.getVoltageVsPWMCurse = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.getVoltageVsPWMCurse.setFocusPolicy(QtCore.Qt.NoFocus)
        self.getVoltageVsPWMCurse.setObjectName("getVoltageVsPWMCurse")
        self.horizontalLayout.addWidget(self.getVoltageVsPWMCurse)
        self.StopVoltageVsPWMCurse = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.StopVoltageVsPWMCurse.setFocusPolicy(QtCore.Qt.NoFocus)
        self.StopVoltageVsPWMCurse.setObjectName("StopVoltageVsPWMCurse")
        self.horizontalLayout.addWidget(self.StopVoltageVsPWMCurse)
        self.savePVFDtoMCU = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.savePVFDtoMCU.setFocusPolicy(QtCore.Qt.NoFocus)
        self.savePVFDtoMCU.setObjectName("savePVFDtoMCU")
        self.horizontalLayout.addWidget(self.savePVFDtoMCU)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "高级设置"))
        self.groupBox.setTitle(_translate("Dialog", "PID设置"))
        self.SetPIDParam.setText(_translate("Dialog", "设置"))
        self.label.setText(_translate("Dialog", "Kp"))
        self.label_2.setText(_translate("Dialog", "Ki"))
        self.label_3.setText(_translate("Dialog", "Kd"))
        self.label_16.setText(_translate("Dialog", "KpF"))
        self.label_17.setText(_translate("Dialog", "KiF"))
        self.label_18.setText(_translate("Dialog", "KdF"))
        self.label_19.setText(_translate("Dialog", "eL"))
        self.label_20.setText(_translate("Dialog", "eM"))
        self.label_21.setText(_translate("Dialog", "eS"))
        self.label_6.setText(_translate("Dialog", "ecM"))
        self.label_8.setText(_translate("Dialog", "ecS"))
        self.label_7.setText(_translate("Dialog", "ecL"))
        self.label_15.setText(_translate("Dialog", "F_Cutoff(Hz)"))
        self.label_22.setText(_translate("Dialog", "SampCycle(ms)"))
        self.label_10.setText(_translate("Dialog", "DeadZone(mv)"))
        self.label_23.setText(_translate("Dialog", "PWM_MAX"))
        self.label_24.setText(_translate("Dialog", "PWM_MIN"))
        self.label_25.setText(_translate("Dialog", "PWM_STEP"))
        self.groupBox_4.setTitle(_translate("Dialog", "调试"))
        self.SetRuningParam.setText(_translate("Dialog", "设置"))
        self.label_5.setText(_translate("Dialog", "SetPoint(mv)"))
        self.groupBox_5.setTitle(_translate("Dialog", "控制"))
        self.label_13.setText(_translate("Dialog", "Start"))
        self.label_12.setText(_translate("Dialog", "End"))
        self.label_14.setText(_translate("Dialog", "StepSize"))
        self.getVoltageVsPWMCurse.setText(_translate("Dialog", "绘制滞回线"))
        self.StopVoltageVsPWMCurse.setText(_translate("Dialog", "停止"))
        self.savePVFDtoMCU.setText(_translate("Dialog", "保存"))

